package filtr;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class Stmt {
  interface Visitor<R> {
    R visitBlockStmt(Block stmt);
    R visitExpressionStmt(Expression stmt);
    R visitFunctionStmt(Function stmt);
    R visitIfStmt(If stmt);
    R visitPrintStmt(Print stmt);
    R visitForStmt(For stmt);
    R visitDropStmt(Drop stmt);
    R visitFillStmt(Fill stmt);
    R visitRenameStmt(Rename stmt);
    R visitAddColumnStmt(AddColumn stmt);
    R visitFilterStmt(Filter stmt);
    R visitExportStmt(Export stmt);
    R visitImportStmt(Import stmt);
    R visitAssignStmt(Assign stmt);
    R visitReturnStmt(Return stmt);
    R visitViewStmt(View stmt);
  }
  static class Block extends Stmt {
    Block(List<Stmt> statements) {
      this.statements = statements;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitBlockStmt(this);
    }

    final List<Stmt> statements;

    @Override
    public String toString() {
      return "Block(" + statements + ")";
    }
  }
  static class Expression extends Stmt {
    Expression(Expr expression) {
      this.expression = expression;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitExpressionStmt(this);
    }

    final Expr expression;

    @Override
    public String toString() {
      return "Expression(" + expression + ")";
    }
  }
  static class Function extends Stmt {
    Function(Token name, List<Token> params, List<Stmt> body) {
      this.name = name;
      this.params = params;
      this.body = body;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitFunctionStmt(this);
    }

    final Token name;
    final List<Token> params;
    final List<Stmt> body;

    @Override
    public String toString() {
      return "Function(" + name + ", " + params + ", " + body + ")";
    }
  }
  static class If extends Stmt {
    If(Expr condition, Stmt thenBranch, Stmt elseBranch) {
      this.condition = condition;
      this.thenBranch = thenBranch;
      this.elseBranch = elseBranch;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitIfStmt(this);
    }

    final Expr condition;
    final Stmt thenBranch;
    final Stmt elseBranch;

    @Override
    public String toString() {
      return "If(" + condition + ", " + thenBranch + ", " + elseBranch + ")";
    }
  }
  static class Print extends Stmt {
    Print(Expr expression) {
      this.expression = expression;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitPrintStmt(this);
    }

    final Expr expression;

    @Override
    public String toString() {
      return "Print(" + expression + ")";
    }
  }
  static class For extends Stmt {
    For(Token mode, Token dataset, Stmt body) {
      this.mode = mode;
      this.dataset = dataset;
      this.body = body;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitForStmt(this);
    }

    final Token mode;
    final Token dataset;
    final Stmt body;

    @Override
    public String toString() {
      return "For(" + mode + ", " + dataset + ", " + body + ")";
    }
  }
  static class Drop extends Stmt {
    Drop(Token keyword, List<Token> identifiers, Token dataset) {
      this.keyword = keyword;
      this.identifiers = identifiers;
      this.dataset = dataset;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitDropStmt(this);
    }

    final Token keyword;
    final List<Token> identifiers;
    final Token dataset;

    @Override
    public String toString() {
      return "Drop(" + keyword + ", " + identifiers + ", " + dataset + ")";
    }
  }
  static class Fill extends Stmt {
    Fill(Token keyword, Token column, Token dataset, Expr value) {
      this.keyword = keyword;
      this.column = column;
      this.dataset = dataset;
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitFillStmt(this);
    }

    final Token keyword;
    final Token column;
    final Token dataset;
    final Expr value;

    @Override
    public String toString() {
      return "Fill(" + keyword + ", " + column + ", " + dataset + ", " + value + ")";
    }
  }
  static class Rename extends Stmt {
    Rename(Token dataset, Token column, Token newName) {
      this.dataset = dataset;
      this.column = column;
      this.newName = newName;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitRenameStmt(this);
    }

    final Token dataset;
    final Token column;
    final Token newName;

    @Override
    public String toString() {
      return "Rename(" + dataset + ", " + column + ", " + newName + ")";
    }
  }
  static class AddColumn extends Stmt {
    AddColumn(Token dataset, Token column, Expr value) {
      this.dataset = dataset;
      this.column = column;
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitAddColumnStmt(this);
    }

    final Token dataset;
    final Token column;
    final Expr value;

    @Override
    public String toString() {
      return "AddColumn(" + dataset + ", " + column + ", " + value + ")";
    }
  }
  static class Filter extends Stmt {
    Filter(Token dataset, Token columnName, Token operator, Expr expression, Token newName) {
      this.dataset = dataset;
      this.columnName = columnName;
      this.operator = operator;
      this.expression = expression;
      this.newName = newName;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitFilterStmt(this);
    }

    final Token dataset;
    final Token columnName;
    final Token operator;
    final Expr expression;
    final Token newName;

    @Override
    public String toString() {
      return "Filter(" + dataset + ", " + columnName + ", " + operator + ", " + expression + ", " + newName + ")";
    }
  }
  static class Export extends Stmt {
    Export(Token keyword, Token dataset, Token path) {
      this.keyword = keyword;
      this.dataset = dataset;
      this.path = path;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitExportStmt(this);
    }

    final Token keyword;
    final Token dataset;
    final Token path;

    @Override
    public String toString() {
      return "Export(" + keyword + ", " + dataset + ", " + path + ")";
    }
  }
  static class Import extends Stmt {
    Import(Token keyword, Token path, Token newName) {
      this.keyword = keyword;
      this.path = path;
      this.newName = newName;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitImportStmt(this);
    }

    final Token keyword;
    final Token path;
    final Token newName;

    @Override
    public String toString() {
      return "Import(" + keyword + ", " + path + ", " + newName + ")";
    }
  }
  static class Assign extends Stmt {
    Assign(Token name, Expr value) {
      this.name = name;
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitAssignStmt(this);
    }

    final Token name;
    final Expr value;

    @Override
    public String toString() {
      return "Assign(" + name + ", " + value + ")";
    }
  }
  static class Return extends Stmt {
    Return(Expr value) {
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitReturnStmt(this);
    }

    final Expr value;

    @Override
    public String toString() {
      return "Return(" + value + ")";
    }
  }
  static class View extends Stmt {
    View(Token dataset) {
      this.dataset = dataset;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitViewStmt(this);
    }

    final Token dataset;

    @Override
    public String toString() {
      return "View(" + dataset + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
